[package]
name = "aries-core"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow.workspace = true
aries-config = { path = "../aries-config" }
aries-theme = { path = "../aries-theme" }
colored.workspace = true
dialoguer.workspace = true
diffy.workspace = true
futures.workspace = true
glob.workspace = true
globset.workspace = true
ignore.workspace = true
itertools.workspace = true
nanoid.workspace = true
parking_lot.workspace = true
regex.workspace = true
reqwest.workspace = true
rig-core.workspace = true
serde.workspace = true
serde_json.workspace = true
serde_yaml.workspace = true
thiserror.workspace = true
tokio = { workspace = true, features = ["fs", "process", "sync"] }
