[package]
name = "aries-agent"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow.workspace = true
aries-extension = { path = "../aries-extension" }
aries-filesystem = { path = "../aries-filesystem" }
aries-lspclient = { path = "../aries-lspclient" }
aries-tools = { path = "../aries-tools" }
futures.workspace = true
git2.workspace = true
itertools.workspace = true
nanoid.workspace = true
regex-lite.workspace = true
rig-core.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tokio = { workspace = true, features = ["fs", "process"] }
tracing.workspace = true
