[package]
name = "aries-agent"
version = "0.1.0"
edition = "2024"

[dependencies]
aries-event = { path = "../aries-event" }
aries-extension = { path = "../aries-extension" }
aries-init = { version = "0.1.0", path = "../aries-init" }
aries-lspclient = { path = "../aries-lspclient" }
aries-mode = { path = "../aries-mode" }
aries-preamble = { path = "../aries-preamble" }
aries-tools = { path = "../aries-tools" }
futures.workspace = true
itertools.workspace = true
reqwest-middleware.workspace = true
rig-agent.workspace = true
thiserror.workspace = true
tokio = { workspace = true, features = ["fs", "process"] }
