[package]
name = "aries-agent"
version = "0.1.0"
edition = "2024"
license.workspace = true
rust-version.workspace = true
authors.workspace = true
description.workspace = true
repository.workspace = true
readme.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
aries-event = { version = "0.1.0", path = "../aries-event" }
aries-extension = { version = "0.1.0", path = "../aries-extension" }
aries-init = { version = "0.1.0", path = "../aries-init" }
aries-lspclient = { version = "0.1.0", path = "../aries-lspclient" }
aries-mode = { version = "0.1.0", path = "../aries-mode" }
aries-preamble = { version = "0.1.0", path = "../aries-preamble" }
aries-tools = { version = "0.1.0", path = "../aries-tools" }
futures.workspace = true
itertools.workspace = true
rig.workspace = true
thiserror.workspace = true
tokio = { workspace = true, features = ["fs", "process"] }
