[package]
name = "aries"
version = "0.1.0"
edition = "2024"
authors = ["ltoddy <taoliu0509@gmail.com>"]
resolver = "3"

[workspace]
members = [
    "crates/aries-acp", "crates/aries-config",
    "crates/aries-context",
    "crates/aries-core", "crates/aries-theme",
]

[workspace.dependencies]
anyhow = "1"
colored = "3"
dialoguer = { version = "0.12", default-features = false, features = ["fuzzy-select"] }
futures = "0.3"
nanoid = "0.4.0"
rig-core = "0.33"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1", default-features = false }

[dependencies]
aries-acp = { path = "crates/aries-acp" }
aries-context = { path = "crates/aries-context" }
aries-config = { path = "crates/aries-config" }
aries-core = { path = "crates/aries-core" }
aries-theme = { path = "crates/aries-theme" }

anyhow.workspace = true
colored.workspace = true
dialoguer.workspace = true
rig-core.workspace = true
serde_json.workspace = true
tokio = { workspace = true, features = ["rt-multi-thread", "macros", "fs", "process"] }

clap = { version = "4", features = ["derive"] }
ferris-says = "0.3.2"
rustyline = "18.0"
rustyline-derive = "0.12"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
whoami = "2.1"
tracing-appender = "0.2"
futures = "0.3.32"

[profile.dev]
debug = 0

[profile.release]
lto = true
codegen-units = 1
panic = "abort"
