[package]
name = "aries-cli"
version = "0.1.0"
edition = "2024"
authors = ["ltoddy <taoliu0509@gmail.com>"]

[[bin]]
name = "aries"
path = "src/main.rs"

[dependencies]
agent-client-protocol.workspace = true
anyhow.workspace = true
aries-acp = { path = "../aries-acp" }
aries-context = { path = "../aries-context" }
aries-core = { path = "../aries-core" }
aries-init = { path = "../aries-init" }
aries-logger = { path = "../aries-logger" }
aries-session = { path = "../aries-session" }
clap = { workspace = true, features = ["derive"] }
colored.workspace = true
dark-light.workspace = true
dialoguer.workspace = true
futures.workspace = true
itertools.workspace = true
nanoid.workspace = true
prettytable-rs.workspace = true
rig-core.workspace = true
rustyline-derive.workspace = true
rustyline.workspace = true
serde_json.workspace = true
terminal_size.workspace = true
tokio = { workspace = true, features = ["rt-multi-thread", "macros", "fs", "process"] }
tracing.workspace = true
