[package]
name = "aries-cli"
version = "0.1.0"
edition = "2024"
license.workspace = true
rust-version.workspace = true
authors.workspace = true
description.workspace = true
repository.workspace = true
readme.workspace = true
keywords.workspace = true
categories.workspace = true

[[bin]]
name = "aries"
path = "src/main.rs"

[dependencies]
agent-client-protocol.workspace = true
anyhow.workspace = true
aries-acp = { version = "0.1.0", path = "../aries-acp" }
aries-event = { version = "0.1.0", path = "../aries-event" }
aries-extension = { version = "0.1.0", path = "../aries-extension" }
aries-init = { version = "0.1.0", path = "../aries-init" }
aries-logger = { version = "0.1.0", path = "../aries-logger" }
aries-persistence = { version = "0.1.0", path = "../aries-persistence" }
aries-session = { version = "0.1.0", path = "../aries-session" }
aries-tokenopt = { version = "0.1.0", path = "../aries-tokenopt" }
aries-tools = { version = "0.1.0", path = "../aries-tools" }
clap = { workspace = true, features = ["derive"] }
colored.workspace = true
dialoguer.workspace = true
ferris-says.workspace = true
futures.workspace = true
itertools.workspace = true
jiff.workspace = true
mimalloc.workspace = true
nanoid.workspace = true
parking_lot.workspace = true
prettytable.workspace = true
rig.workspace = true
rustyline.workspace = true
rustyline-derive.workspace = true
serde_json.workspace = true
terminal_size.workspace = true
tokio = { workspace = true, features = ["rt-multi-thread", "macros", "fs", "process"] }
tracing.workspace = true
tree-sitter.workspace = true
tree-sitter-bash.workspace = true
