[package]
name = "aries-compact"
version = "0.1.0"
edition = "2024"
license.workspace = true
rust-version.workspace = true
authors.workspace = true
description.workspace = true
repository.workspace = true
readme.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
anyhow.workspace = true
aries-context = { version = "0.1.0", path = "../aries-context" }
aries-event = { version = "0.1.0", path = "../aries-event" }
aries-extension = { version = "0.1.0", path = "../aries-extension" }
aries-filesystem = { version = "0.1.0", path = "../aries-filesystem" }
aries-tools = { version = "0.1.0", path = "../aries-tools" }
futures.workspace = true
parking_lot.workspace = true
regex-lite.workspace = true
rig = { workspace = true, features = ["reqwest-middleware"] }
serde_json.workspace = true
tokio = { workspace = true, features = ["fs"] }

[dev-dependencies]
tempfile.workspace = true
tokio = { workspace = true, features = ["fs", "macros", "rt"] }
