[package]
name = "aries-filesystem"
version = "0.1.0"
edition = "2024"

[dependencies]
fs4 = { workspace = true, features = ["tokio"] }
git2.workspace = true
ignore.workspace = true
itertools.workspace = true
serde.workspace = true
serde_json.workspace = true
serde_yaml.workspace = true
thiserror.workspace = true
tokio = { workspace = true, features = ["fs", "rt-multi-thread", "macros"] }
url.workspace = true
