[package]
name = "aries-preamble"
version = "0.1.0"
edition = "2024"
license.workspace = true
rust-version.workspace = true
authors.workspace = true
description.workspace = true
repository.workspace = true
readme.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
aries-extension = { version = "0.1.0", path = "../aries-extension" }
aries-filesystem = { version = "0.1.0", path = "../aries-filesystem" }
aries-init = { version = "0.1.0", path = "../aries-init" }
git2.workspace = true
itertools.workspace = true
jiff.workspace = true
