[package]
name = "aries-lspclient"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow.workspace = true
aries-filesystem = { path = "../aries-filesystem" }
parking_lot.workspace = true
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
serde_repr.workspace = true
tokio = { workspace = true, features = ["process", "io-util", "sync", "time"] }
tracing.workspace = true
