[package]
name = "aries"
version = "0.1.0"
edition = "2024"
authors = ["ltoddy <taoliu0509@gmail.com>"]

[[bin]]
name = "aries"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
aries-acp = { path = "../aries-acp" }
aries-config = { path = "../aries-config" }
aries-context = { path = "../aries-context" }
aries-core = { path = "../aries-core" }
aries-session = { path = "../aries-session" }
aries-theme = { path = "../aries-theme" }
clap = { workspace = true, features = ["derive"] }
dialoguer.workspace = true
itertools.workspace = true
rig-core.workspace = true
rustyline.workspace = true
rustyline-derive.workspace = true
serde_json.workspace = true
terminal_size.workspace = true
tokio = { workspace = true, features = ["rt-multi-thread", "macros", "fs", "process"] }
