[package]
name = "aries-acp"
version = "0.1.0"
edition = "2024"
license.workspace = true
rust-version.workspace = true
authors.workspace = true
description.workspace = true
repository.workspace = true
readme.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
agent-client-protocol = { workspace = true, features = ["unstable_protocol_v2", "unstable"] }
aries-event = { version = "0.1.0", path = "../aries-event" }
aries-extension = { version = "0.1.0", path = "../aries-extension" }
aries-init = { version = "0.1.0", path = "../aries-init" }
aries-mode = { version = "0.1.0", path = "../aries-mode" }
aries-session = { version = "0.1.0", path = "../aries-session" }
aries-tools = { version = "0.1.0", path = "../aries-tools" }
base64.workspace = true
itertools.workspace = true
rig.workspace = true
serde_json.workspace = true
tokio = { workspace = true, features = ["net", "sync"] }
tokio-util = { workspace = true, features = ["compat"] }
tracing.workspace = true
