[package]
name = "aries-memory"
version = "0.1.0"
edition = "2024"

[dependencies]
aries-filesystem = { path = "../aries-filesystem" }
aries-tools = { path = "../aries-tools" }
itertools.workspace = true
rig.workspace = true
schemars.workspace = true
serde = { workspace = true, features = ["derive"] }
tokio = { workspace = true, features = ["io-util"] }
tracing.workspace = true
